# Calculo de las distancias

In [4]:
import numpy as np
from matplotlib import pyplot as plt
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (12, 6)

In [10]:
data = np.array([[8,10],[3,10.5],[7,13.5],[5,18],[5,13],[6,9],[9,11],[3,18],[8.5,12],[8,16]])
C = np.array([[8,10],[3,10.5]])

fig = plt.figure()
plt.scatter(C[0][0], C[0][1], marker='*', s=200, c='k')
plt.scatter(C[1][0], C[1][1], marker='*', s=200, c='k')
plt.scatter(data[:,0], data[:,1])

In [14]:
distances = []
clusters = np.zeros(len(data))

def dist(a, b, ax=1):
    return np.linalg.norm(a-b, axis=ax)

for i in range(len(data)):
    distance = dist(data[i], C)
    distances.append(distance)
    cluster = np.argmin(distance)
    clusters[i] = cluster
    
print(clusters)
distances
    

[0. 1. 0. 1. 1. 0. 0. 1. 0. 0.]


[array([0.        , 5.02493781]),
 array([5.02493781, 0.        ]),
 array([3.64005494, 5.        ]),
 array([8.54400375, 7.76208735]),
 array([4.24264069, 3.20156212]),
 array([2.23606798, 3.35410197]),
 array([1.41421356, 6.02079729]),
 array([9.43398113, 7.5       ]),
 array([2.06155281, 5.70087713]),
 array([6.        , 7.43303437])]

In [19]:
for i in range(len(C)):
    points = [data[j] for j in range(len(data)) if clusters[j] == i]
    print(points)
    C[i] = np.mean(points, axis=0)
C

[array([ 8., 10.]), array([ 7. , 13.5]), array([6., 9.]), array([ 9., 11.]), array([ 8.5, 12. ]), array([ 8., 16.])]
[array([ 3. , 10.5]), array([ 5., 18.]), array([ 5., 13.]), array([ 3., 18.])]


array([[ 7.75      , 11.91666667],
       [ 4.        , 14.875     ]])

Se pueden ver los dos grupos con su respectivo centroide.

In [18]:
fig = plt.figure()
plt.scatter(C[0][0], C[0][1], marker='*', s=200, c='k')
plt.scatter(C[1][0], C[1][1], marker='*', s=200, c='k')
plt.scatter(data[:,0], data[:,1])