# Programa 4

### Integrantes
- Silva Velázquez Elsy Camila
- Longines Tapia Hugo Didier
- Andrés Urbano Guillermo Gerardo

---

♦ Implementar el cálculo del estimador:

$βˆ = (X^T X − λI)^{−1} X^Ty$

♦ Iterar el modelo de regresión Ridge variando el valor de λ para obtener el mejor para el
ejemplo con datos artificiales (de preferencia con la implementación propia).

♦ Revisar el uso de las regresiones Lasso y ElasticNet.

In [ ]:
import numpy as np

In [ ]:
def estimador_B(X, y):    
    """    
    Genera el estimador B.
    
    Param-
    X -- es una matriz nxq donde el i-esimo renglon es el valor predictivo xi.
    y -- es el vector de los n valores observados.    
    
    X^T X debe ser invertible.
    
    Return
    Es un vector de números reales y longitud q. 
    """
    det = None                
    X1 = np.linalg.inv(np.dot(X.T, X))
    try:
        det = np.linalg.det(X1)  
    except:
        return "Su matriz debe ser cuadrada"
    if (det == 0):
        return 'Su matriz no tiene inversa'
    X2 = np.dot(X.T, y)
    B = np.dot(X1, X2)
    return B

In [ ]:
# X = np.array([ [4,3,2], [5,0,1], [4,3,2]]) # Esta matriz no tiene inversa
# X = np.random.rand(3,3) # matriz
# y = np.random.rand(X.shape[0])

# Pruba
X = np.array([[0.3 , 1.  ],
       [0.64, 1.  ],
       [0.99, 1.  ],
       [1.33, 1.  ],
       [1.67, 1.  ],
       [2.01, 1.  ],
       [2.36, 1.  ],
       [2.7 , 1.  ]])

y = np.array([[0.15],
       [0.11],
       [0.02],
       [0.43],
       [0.39],
       [0.62],
       [0.72],
       [0.81]])

estimador_B(X, y)

array([[ 0.32727052],
       [-0.08465578]])

In [ ]:
def sigma_2(X, y, B):
    """
    Calcula la varianza
    
    Param:
    X -- es una matriz nxq donde el i-esimo renglon es el valor predictivo xi.
    y -- es el vector de los n valores observados.    
    B -- Es un vector de números reales y longitud q
    
    Return
    Es un vector de números reales y longitud q. 
    """
    yv = []
    for i in range(len(X)):
        yv.append(list(np.dot(X[i].T, B)))
    sumas = []
    for i in range(len(y)):
        sumas.append((y[i]-yv[i])**2)
    
    sigma = sum(sumas)/(len(X) - len(X.T))
    return sigma

In [ ]:
sigma_2(X, y, estimador_B(X, y))

array([0.01363063])

In [ ]:
def var_b(X, sigma):
    """Calcula la varianza de B
    
    Param:
    X -- es una matriz nxq donde el i-esimo renglon es el valor predictivo xi.
    sigma - varianza 
    """
    X1 = np.linalg.inv(np.dot(X.T, X))
    var = sigma * X1
    return var

In [ ]:
var_b(X, sigma_2(X, y, estimador_B(X, y)))

array([[ 0.0027608 , -0.0041412 ],
       [-0.0041412 ,  0.00791563]])